import type { ImageSourcePropType } from 'react-native';

/** Official league badges, keyed by the league name stored on the roster. */
export const LEAGUE_LOGO: Record<string, ImageSourcePropType> = {
  'לה ליגה': require('@/assets/crests/laliga.png'),
  'פרמייר ליג': require('@/assets/crests/premier.png'),
  'ליג 1': require('@/assets/crests/ligue1.png'),
  'בונדסליגה': require('@/assets/crests/bundesliga.png'),
  'סרייה א׳': require('@/assets/crests/seriea.png'),
  MLS: require('@/assets/crests/mls.png'),
  WSL: require('@/assets/crests/wsl.png'),
  NWSL: require('@/assets/crests/nwsl.png'),
  'ליגה פורטוגל': require('@/assets/crests/ligaportugal.png'),
  'ארדיוויזי': require('@/assets/crests/eredivisie.png'),
  'Nederland Vrouwen Liga': require('@/assets/crests/eredivisiew.jpg'),
  'ליגת העל הסעודית': require('@/assets/crests/saudi.png'),
  'סופר ליג': require('@/assets/crests/superlig.png'),
  'הצ׳מפיונשיפ': require('@/assets/crests/championship.png'),
  'ליגת העל הסקוטית': require('@/assets/crests/scottish.png'),
  'Liga BBVA MX': require('@/assets/crests/ligamx.png'),
  'Hellas Liga': require('@/assets/crests/greece.png'),
  '1A Pro League': require('@/assets/crests/belgium.png'),
  'ליגת העל הבלגית': require('@/assets/crests/belgium.png'),
  LPF: require('@/assets/crests/lpf.png'),
  'ליגת העל הארגנטינאית': require('@/assets/crests/lpf.png'),
  'Bundesliga 2': require('@/assets/crests/bundes2.png'),
  'LALIGA HYPERMOTION': require('@/assets/crests/hyper.png'),
  'Česká Liga': require('@/assets/crests/czech.png'),
  'CONMEBOL Libertadores': require('@/assets/crests/libertadores.png'),
  'CONMEBOL Sudamericana': require('@/assets/crests/sudamericana.png'),
  'Serie BKT': require('@/assets/crests/serieb.png'),
  Ekstraklasa: require('@/assets/crests/ekstraklasa.png'),
  CSL: require('@/assets/crests/csl.png'),
  'Ligue 2 BKT': require('@/assets/crests/ligue2.png'),
  'Brack Super League': require('@/assets/crests/swiss.png'),
  'Ukrayina Liha': require('@/assets/crests/ukraine.png'),
  Allsvenskan: require('@/assets/crests/allsvenskan.png'),
  'Sverige Liga': require('@/assets/crests/sverige.png'),
  Eliteserien: require('@/assets/crests/eliteserien.png'),
  'Liga do Brasil': require('@/assets/crests/brasil.png'),
  'K League 1': require('@/assets/crests/kleague.png'),
  'Liga Hrvatska': require('@/assets/crests/croatia.png'),
  'Liga Colombia': require('@/assets/crests/colombia.png'),
  'Liga Bulgaria': require('@/assets/crests/bulgaria.png'),
  'United Emirates League': require('@/assets/crests/uae.png'),
  'Ö. Bundesliga': require('@/assets/crests/austria.png'),
  SUPERLIGA: require('@/assets/crests/romania.png'),
  'Metropolitan Division': require('@/assets/crests/denmark.png'),
  'Magyar Liga': require('@/assets/crests/hungary.png'),
  'Thailand League': require('@/assets/crests/thailand.png'),
  'EFL League One': require('@/assets/crests/leagueone.png'),
  'Liga Azerbaijan': require('@/assets/crests/azerbaijan.png'),
  'Liga F Moeve': require('@/assets/crests/ligaf.png'),
  'ליגה F': require('@/assets/crests/ligaf.png'),
  GPFBL: require('@/assets/crests/frauen.png'),
  'בונדסליגה נשים': require('@/assets/crests/frauen.png'),
  'Arkema PL': require('@/assets/crests/arkema.png'),
  'ליג 1 נשים': require('@/assets/crests/arkema.png'),
  'Liga Portugal Feminino': require('@/assets/crests/ptwomen.png'),
  'Calcio A Femminile': require('@/assets/crests/serieaw.png'),
  "Scottish Women's League": require('@/assets/crests/scotw.png'),
  'Premier League': require('@/assets/crests/premier.png'),
  Bundesliga: require('@/assets/crests/bundesliga.png'),
  'Ligue 1 McDonald\'s': require('@/assets/crests/ligue1.png'),
  'Serie A Enilive': require('@/assets/crests/seriea.png'),
  'Google Pixel Frauen-Bundesliga': require('@/assets/crests/frauen.png'),
  'LALIGA EA SPORTS': require('@/assets/crests/laliga.png'),
  Eredivisie: require('@/assets/crests/eredivisie.png'),
  'Liga Portugal': require('@/assets/crests/ligaportugal.png'),
  'Liga Profesional de Fútbol': require('@/assets/crests/lpf.png'),
  'Arkema Première Ligue': require('@/assets/crests/arkema.png'),
  'Major League Soccer': require('@/assets/crests/mls.png'),
  'Scottish Premiership': require('@/assets/crests/scottish.png'),
  'Barclays Women’s Super League': require('@/assets/crests/wsl.png'),
  'Saudi Pro League': require('@/assets/crests/saudi.png'),
  'ROSHN Saudi League': require('@/assets/crests/saudi.png'),
};
