/** Hebrew (and common English) nation labels → flagcdn ISO codes. */
const ISO: Record<string, string> = {
  ישראל: 'il',
  Israel: 'il',
  סקוטלנד: 'gb-sct',
  פורטוגל: 'pt',
  צרפת: 'fr',
  ספרד: 'es',
  ברזיל: 'br',
  אנגליה: 'gb-eng',
  ארגנטינה: 'ar',
  גרמניה: 'de',
  הולנד: 'nl',
  נורווגיה: 'no',
  איטליה: 'it',
  בלגיה: 'be',
  קרואטיה: 'hr',
  מרוקו: 'ma',
  יפן: 'jp',
  'ארה״ב': 'us',
  'ארה"ב': 'us',
  ניגריה: 'ng',
  סנגל: 'sn',
  פולין: 'pl',
  אורוגוואי: 'uy',
  גאורגיה: 'ge',
  שוודיה: 'se',
  דנמרק: 'dk',
  מצרים: 'eg',
  קוריאה: 'kr',
  קולומביה: 'co',
  טורקיה: 'tr',
  שווייץ: 'ch',
  הונגריה: 'hu',
  אוקראינה: 'ua',
  קנדה: 'ca',
  סלובניה: 'si',
  גבון: 'ga',
  'צ׳כיה': 'cz',
  "צ'כיה": 'cz',
  סרביה: 'rs',
  'אלג׳יריה': 'dz',
  "אלג'יריה": 'dz',
  אוסטריה: 'at',
  יוון: 'gr',
  מקסיקו: 'mx',
  'חוף השנהב': 'ci',
  קמרון: 'cm',
  גאנה: 'gh',
  מאלי: 'ml',
  ויילס: 'gb-wls',
  אירלנד: 'ie',
  'רפובליקת אירלנד': 'ie',
  פינלנד: 'fi',
  אוסטרליה: 'au',
  זמביה: 'zm',
  'צ׳ילה': 'cl',
  "צ'ילה": 'cl',
  'ג׳מייקה': 'jm',
  "ג'מייקה": 'jm',
  רומניה: 'ro',
  סלובקיה: 'sk',
  בולגריה: 'bg',
  אקוודור: 'ec',
  פרו: 'pe',
  פרגוואי: 'py',
  ונצואלה: 've',
  'קוסטה ריקה': 'cr',
  'בורקינה פאסו': 'bf',
  'Burkina Faso': 'bf',
  קונגו: 'cg',
  Congo: 'cg',
  'הרפובליקה הדמוקרטית של קונגו': 'cd',
  'DR Congo': 'cd',
  Spain: 'es',
  France: 'fr',
  Brazil: 'br',
  England: 'gb-eng',
  Germany: 'de',
  Italy: 'it',
  Portugal: 'pt',
  Argentina: 'ar',
  Netherlands: 'nl',
  Belgium: 'be',
  Norway: 'no',
  Scotland: 'gb-sct',
  Wales: 'gb-wls',
  Ireland: 'ie',
  'Republic of Ireland': 'ie',
  Jamaica: 'jm',
  Croatia: 'hr',
  Morocco: 'ma',
  Japan: 'jp',
  'United States': 'us',
  USA: 'us',
  Ghana: 'gh',
  Slovakia: 'sk',
  Australia: 'au',
  Bulgaria: 'bg',
  Colombia: 'co',
  Mexico: 'mx',
  Sweden: 'se',
  Czechia: 'cz',
  'Czech Republic': 'cz',
  Peru: 'pe',
  'Saudi Arabia': 'sa',
  'South Korea': 'kr',
  Poland: 'pl',
  'Republic Ireland': 'ie',
  Chile: 'cl',
  Finland: 'fi',
  Nigeria: 'ng',
  Uruguay: 'uy',
};

export function nationIso(nation: string): string | null {
  if (!nation) return null;
  return ISO[nation] ?? ISO[nation.trim()] ?? null;
}

export function nationFlagUri(nation: string, width = 40): string | null {
  const iso = nationIso(nation);
  if (!iso) return null;
  return `https://flagcdn.com/w${width}/${iso}.png`;
}
