import { C, L, N, PLAYERS, type FcPlayer } from '@/lib/fcPlayers';
import { isOpen } from '@/lib/selectors';
import type { SbcChallenge } from '@/lib/types';

export const RETIRED_SBC_IDS = new Set(['sbc-upgrade', 'sbc-puzzle']);

/** Weekly MM set from 17 Sep 2026 — expires 24 Sep 18:00 UTC per EA / FUTBIN. */
const MM_ENDS = '2026-09-24T18:00:00.000Z';
const BOUADDI_ENDS = '2026-09-24T18:00:00.000Z';
const MADRID_DREAMS_ENDS = '2026-09-26T18:00:00.000Z';
const UPGRADE_83_ENDS = '2026-09-29T18:00:00.000Z';
const UPGRADE_79_ENDS = '2026-09-28T18:00:00.000Z';
/** International-break Marquee Matchups. Expires 1 Oct 2026 18:00 UTC. */
const MM_INTL_ENDS = '2026-10-01T18:00:00.000Z';

const OLISE_ENDS = '2026-10-29T15:00:00.000Z';
const RAPHINHA_ENDS = '2026-10-30T16:00:00.000Z';
const TARCIANE_ENDS = '2026-10-11T17:00:00.000Z';
const AKLIOUCHE_ENDS = '2026-10-09T17:00:00.000Z';
const GROSS_ENDS = '2026-10-30T11:00:00.000Z';
const MALEN_ENDS = '2026-10-29T13:00:00.000Z';
const FRATTESI_ENDS = '2026-10-06T17:00:00.000Z';
const PINA_ENDS = null;

export const NATION_DRILL_SQUAD: Record<string, string> = {
  gk: 'alisson',
  lb: 'robertson',
  lcb: 'vandijk',
  rcb: 'saliba',
  rb: 'porro',
  lcm: 'odegaard',
  cm: 'macallister',
  rcm: 'szoboszlai',
  lw: 'diaz',
  st: 'isak',
  rw: 'son',
};

export const MADRID_DREAMS_SQUAD: Record<string, string> = {
  gk: 'courtois',
  lb: 'robertson',
  lcb: 'militao',
  rcb: 'vandijk',
  rb: 'hakimi',
  lcm: 'valverde',
  cm: 'vitinha',
  rcm: 'neves',
  lw: 'galeno',
  st: 'alisson',
  rw: 'costa',
};

/** Live international MM, 24 Sep–1 Oct 2026. Requirements from FUT.GG; no cheapest 11 was published there. */
const MM_ITALY_SQUAD: Record<string, string> = {
  gk: 'ea-223957-lucas-pirard',
  lb: 'ea-251911-mardochee-nzita',
  lcb: 'ea-263703-henry-lawrence',
  rcb: 'ea-278750-reno-munz',
  rb: 'ea-206269-laurent-jans',
  lcm: 'ea-209701-joey-pelupessy',
  cm: 'ea-210831-birger-verstraete',
  rcm: 'ea-242753-alexis-trouillet',
  lw: 'ea-271953-momodou-lamin-sonko',
  st: 'ea-245565-mouhamed-belkheir',
  rw: 'ea-246713-ken-nkuba',
};

const MM_NORWAY_SQUAD: Record<string, string> = {
  gk: 'ea-87893-michaely-bihina',
  lb: 'ea-273280-marit-bratberg-lund',
  lcb: 'ea-261853-diana-gomes',
  rcb: 'ea-261831-ana-borges',
  rb: 'ea-261858-catarina-amado',
  lcm: 'ea-73230-beatriz-cameirao',
  cm: 'ea-77246-rakel-engesvik',
  rcm: 'ea-275932-pauleta',
  lw: 'ea-275927-nycole-raysla',
  st: 'ea-87899-ziqin-shao',
  rw: 'ea-70851-chandra-davidson',
};

const MM_NETHERLANDS_SQUAD: Record<string, string> = {
  gk: 'ea-263272-philipp-schulze',
  lb: 'ea-234760-arkadiusz-reca',
  lcb: 'ea-199763-bartosz-bereszynski',
  rcb: 'ea-238703-arvid-brorsson',
  rb: 'ea-269506-dominik-pia',
  lcm: 'ea-224146-jesus-imaz',
  cm: 'ea-212249-sebastian-kerk',
  rcm: 'ea-218746-jose-pozo',
  lw: 'ea-233470-borja-galan',
  st: 'ea-206626-mikael-ishak',
  rw: 'ea-222329-mateusz-wdowiak',
};

const MM_ENGLAND_SQUAD: Record<string, string> = {
  gk: 'ea-247796-ellie-roebuck',
  lb: 'ea-265705-marisa-olislagers',
  lcb: 'ea-239756-tuva-hansen',
  rcb: 'ea-246207-allyson-swaby',
  rb: 'ea-265252-ashleigh-neville',
  lcm: 'ea-265292-maisie-symonds',
  cm: 'ea-72791-oona-siren',
  rcm: 'ea-80614-lucia-kendall',
  lw: 'ea-74404-rosa-kafaji',
  st: 'ea-265975-kelly-gago',
  rw: 'ea-78685-lisa-baum',
};

/** FUT.GG cheapest gold upgrade, 17 Sep 2026. The SBC has no chemistry requirement. */
const GOLD_UPGRADE_SQUAD: Record<string, string> = {
  gk: 'ea-203980-konstantinos-fortounis',
  lb: 'ea-226790-wilfred-ndidi',
  lcb: 'ea-248231-hernan-lopez-munoz',
  rcb: 'ea-253727-lukas-provod',
  rb: 'ea-256115-lazar-samardzic',
  lcm: 'ea-228946-mattias-svanberg',
  cm: 'ea-271739-honoka-hayashi',
  rcm: 'ea-276602-assan-ouedraogo',
  lw: 'ea-246786-valentina-bergamaschi',
  st: 'ea-262580-darko-nejasmic',
  rw: 'ea-271839-selina-vobian',
};

const SILVER_UPGRADE_SQUAD: Record<string, string> = {
  gk: 'ea-220532-nikita-contini',
  lb: 'ea-276705-edoardo-pieragnolo',
  lcb: 'ea-271882-sebastian-otoa',
  rcb: 'ea-278305-lorenzo-lucchesi',
  rb: 'ea-271006-yeferson-paz',
  lcm: 'ea-243527-fabrizio-caligara',
  cm: 'ea-253120-ben-lhassine-kone',
  rcm: 'ea-264372-nicolas-galazzi',
  lw: 'ea-71730-agustin-albarracin',
  st: 'ea-257104-kieron-bowie',
  rw: 'ea-247668-konan-ndri',
};

export const officialChallenges: SbcChallenge[] = [
  {
    id: 'sbc-potm-pina',
    title: 'Liga F POTM · קלאודיה פינה',
    kind: 'streamlined',
    requirements: 'פרס שחקן SBC: Claudia Pina 89 LW. שחקנית החודש של Liga F לחודש ספטמבר.',
    endsAt: PINA_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: 'Claudia Pina 89 LW',
    previewFormation: null,
    previewSquad: null,
    clubs: [],
    nations: [N.spain],
    createdAt: '2026-10-06T18:00:00.000Z',
  },
  {
    id: 'sbc-upgrade-80x5',
    title: 'שדרוג 5×80+',
    kind: 'streamlined',
    requirements: 'שדרוג פעיל: חבילה עם 5 שחקני זהב בדירוג 80 ומעלה.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: '5× שחקני זהב 80+',
    previewFormation: null,
    previewSquad: null,
    clubs: [],
    nations: [],
    createdAt: '2026-10-06T18:00:00.000Z',
  },
  {
    id: 'sbc-upgrade-79x3',
    title: 'שדרוג 3×79+',
    kind: 'streamlined',
    requirements: 'שדרוג פעיל: חבילה עם 3 שחקני זהב בדירוג 79 ומעלה.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: '3× שחקני זהב 79+',
    previewFormation: null,
    previewSquad: null,
    clubs: [],
    nations: [],
    createdAt: '2026-10-06T18:00:00.000Z',
  },
  {
    id: 'sbc-dfg-akliouche',
    title: 'Destined For Glory · Maghnes Akliouche',
    kind: 'classic',
    requirements: 'פרס שחקן SBC: Maghnes Akliouche 85 CAM. נתוני קלף: 84 PAC, 83 SHO, 86 PAS, 89 DRI, 55 DEF, 70 PHY.',
    endsAt: AKLIOUCHE_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: 'Maghnes Akliouche 85 CAM',
    previewFormation: null,
    previewSquad: null,
    clubs: [],
    nations: [N.france],
    createdAt: '2026-10-01T17:00:00.000Z',
  },
  {
    id: 'sbc-dfg-tarciane',
    title: 'Destined For Glory · Tarciane',
    kind: 'classic',
    requirements: 'פרס שחקן SBC: Tarciane 84 CB. נתוני קלף: 80 PAC, 45 SHO, 74 PAS, 70 DRI, 84 DEF, 87 PHY.',
    endsAt: TARCIANE_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: 'Tarciane 84 CB',
    previewFormation: null,
    previewSquad: null,
    clubs: [],
    nations: [N.brazil],
    createdAt: '2026-10-01T17:00:00.000Z',
  },
  {
    id: 'sbc-potm-raphinha',
    title: 'LaLiga POTM · Raphinha',
    kind: 'classic',
    requirements: 'פרס שחקן SBC: Raphinha 89 ST. נתוני קלף: 92 PAC, 87 SHO, 86 PAS, 88 DRI, 55 DEF, 77 PHY.',
    endsAt: RAPHINHA_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: 'Raphinha 89 ST',
    previewFormation: null,
    previewSquad: null,
    clubs: [],
    nations: [N.brazil],
    createdAt: '2026-10-02T16:00:00.000Z',
  },
  {
    id: 'sbc-potm-gross',
    title: 'Premier League POTM · Pascal Groß',
    kind: 'classic',
    requirements: 'פרס שחקן SBC: Pascal Groß 84 CDM. נתוני קלף: 76 PAC, 79 SHO, 88 PAS, 83 DRI, 77 DEF, 79 PHY.',
    endsAt: GROSS_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: 'Pascal Groß 84 CDM',
    previewFormation: null,
    previewSquad: null,
    clubs: [],
    nations: [N.germany],
    createdAt: '2026-10-01T11:00:00.000Z',
  },
  {
    id: 'sbc-potm-olise',
    title: 'Bundesliga POTM · Michael Olise',
    kind: 'classic',
    requirements: 'פרס שחקן SBC: Michael Olise 91 RW. נתוני קלף: 84 PAC, 83 SHO, 90 PAS, 92 DRI, 48 DEF, 70 PHY.',
    endsAt: OLISE_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: 'Michael Olise 91 RW',
    previewFormation: null,
    previewSquad: null,
    clubs: [],
    nations: [N.france],
    createdAt: '2026-10-01T15:00:00.000Z',
  },
  {
    id: 'sbc-potm-malen',
    title: 'Serie A POTM · Donyell Malen',
    kind: 'classic',
    requirements: 'פרס שחקן SBC: Donyell Malen 85 ST. נתוני קלף: 87 PAC, 85 SHO, 75 PAS, 86 DRI, 39 DEF, 70 PHY.',
    endsAt: MALEN_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: 'Donyell Malen 85 ST',
    previewFormation: null,
    previewSquad: null,
    clubs: [],
    nations: [N.netherlands],
    createdAt: '2026-10-01T13:00:00.000Z',
  },
  {
    id: 'sbc-dfg-frattesi',
    title: 'Destined For Glory · Davide Frattesi',
    kind: 'classic',
    requirements: 'פרס שחקן SBC: Davide Frattesi 84 CM. נתוני קלף: 84 PAC, 81 SHO, 81 PAS, 84 DRI, 77 DEF, 78 PHY.',
    endsAt: FRATTESI_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: 'Davide Frattesi 84 CM',
    previewFormation: null,
    previewSquad: null,
    clubs: [],
    nations: [N.italy],
    createdAt: '2026-10-01T17:00:00.000Z',
  },


  {
    id: 'sbc-mm-italy',
    title: 'מרקי מאצ׳אפס · איטליה נגד בלגיה',
    kind: 'classic',
    requirements:
      'לפחות שחקן אחד מאיטליה או מבלגיה, לפחות 3 מועדונים, לפחות 3 שחקני כסף, וכימיה 14. הפרס: חבילת זהב מיני.',
    endsAt: MM_INTL_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: {
      chemistry: 14,
      nationsAtLeast: { nations: [N.italy, N.belgium], count: 1 },
      minClubs: 3,
      minSilver: 3,
    },
    reward: 'חבילת זהב מיני',
    previewFormation: '433',
    previewSquad: MM_ITALY_SQUAD,
    clubs: [],
    nations: [N.italy, N.belgium],
    createdAt: '2026-09-24T18:00:00.000Z',
  },
  {
    id: 'sbc-mm-norway',
    title: 'מרקי מאצ׳אפס · נורווגיה נגד פורטוגל',
    kind: 'classic',
    requirements:
      'לפחות שחקן אחד מנורווגיה או מפורטוגל, לפחות 3 מאותו מועדון, עד 5 ליגות, לפחות 2 זהב, כל הכרטיסים מכסף ומעלה, וכימיה 18. הפרס: חבילת שחקנים מעורבת קטנה.',
    endsAt: MM_INTL_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: {
      chemistry: 18,
      nationsAtLeast: { nations: [N.norway, N.portugal], count: 1 },
      minSameClub: 3,
      maxLeagues: 5,
      minGold: 2,
      minQuality: 'silver',
    },
    reward: 'חבילת שחקנים מעורבת קטנה',
    previewFormation: '433',
    previewSquad: MM_NORWAY_SQUAD,
    clubs: [],
    nations: [N.norway, N.portugal],
    createdAt: '2026-09-24T18:00:00.000Z',
  },
  {
    id: 'sbc-mm-netherlands',
    title: 'מרקי מאצ׳אפס · הולנד נגד גרמניה',
    kind: 'classic',
    requirements:
      'לפחות 2 מהולנד או מגרמניה, עד 2 מאותו מועדון, לפחות 4 מאותה ליגה, לפחות 2 זהב, כל הכרטיסים מכסף ומעלה, וכימיה 22. הפרס: חבילת שחקני זהב קטנה.',
    endsAt: MM_INTL_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: {
      chemistry: 22,
      nationsAtLeast: { nations: [N.netherlands, N.germany], count: 2 },
      maxSameClub: 2,
      minSameLeague: 4,
      minGold: 2,
      minQuality: 'silver',
    },
    reward: 'חבילת שחקני זהב קטנה',
    previewFormation: '433',
    previewSquad: MM_NETHERLANDS_SQUAD,
    clubs: [],
    nations: [N.netherlands, N.germany],
    createdAt: '2026-09-24T18:00:00.000Z',
  },
  {
    id: 'sbc-mm-england',
    title: 'מרקי מאצ׳אפס · אנגליה נגד ספרד',
    kind: 'classic',
    requirements:
      'לפחות 2 מאנגליה או מספרד, לפחות 4 מאותה מדינה, עד 3 מאותו מועדון, עד 5 ליגות, דירוג קבוצה 75, וכימיה 26. הפרס: חבילת אלקטראם גדולה.',
    endsAt: MM_INTL_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: {
      chemistry: 26,
      nationsAtLeast: { nations: [N.england, N.spain], count: 2 },
      sameNationAtLeast: 4,
      maxSameClub: 3,
      maxLeagues: 5,
      minRating: 75,
    },
    reward: 'חבילת אלקטראם גדולה',
    previewFormation: '433',
    previewSquad: MM_ENGLAND_SQUAD,
    clubs: [],
    nations: [N.england, N.spain],
    createdAt: '2026-09-24T18:00:00.000Z',
  },
  {
    id: 'sbc-veiga',
    title: 'Destined for Glory · רנאטו וייגה',
    kind: 'streamlined',
    requirements: 'Streamlined: 25,000 נקודות פריט עבור כרטיס Destined for Glory של רנאטו וייגה.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: 25000,
    rules: null,
    reward: 'כרטיס Destined for Glory',
    clubs: [],
    createdAt: '2026-09-25T18:00:00.000Z',
  },
  {
    id: 'sbc-nusa',
    title: 'Destined for Glory · אנטוניו נוסה',
    kind: 'streamlined',
    requirements: 'Streamlined: 75,000 נקודות פריט עבור כרטיס Destined for Glory של אנטוניו נוסה.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: 75000,
    rules: null,
    reward: 'כרטיס Destined for Glory',
    clubs: [],
    createdAt: '2026-09-25T18:00:00.000Z',
  },
  {
    id: 'sbc-dfg-1',
    title: 'Destined for Glory · אתגר 1',
    kind: 'streamlined',
    requirements: 'אתגר הפתיחה של Destined for Glory. הפרס שפורסם: חבילת זהב קטנה.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: 'חבילת זהב קטנה',
    clubs: [],
    createdAt: '2026-09-25T18:00:00.000Z',
  },
  {
    id: 'sbc-totw-upgrade',
    title: 'שדרוג TOTW',
    kind: 'streamlined',
    requirements: 'מגישים פריטים ומקבלים חבילה עם שחקן TOTW מהסבבים 1–3.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: 'חבילת TOTW 1–3',
    clubs: [],
    createdAt: '2026-09-25T18:00:00.000Z',
  },
  {
    id: 'sbc-intro-espinoza',
    title: 'היכרות עם SBC שחקנים · כריסטיאן אספינוזה',
    kind: 'streamlined',
    requirements: 'Streamlined: 4,000 נקודות פריט. הפרס: כרטיס Squad Foundations של כריסטיאן אספינוזה.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: 4000,
    rules: null,
    reward: 'כרטיס Squad Foundations',
    clubs: [],
    createdAt: '2026-09-25T18:00:00.000Z',
  },
  {
    id: 'sbc-madrid-dreams',
    title: 'חלומות מדריד · יאן דיומנדה',
    kind: 'classic',
    requirements:
      'חוגגים את מעברו של יאן דיומנדה לריאל מדריד. עד 4 מאותה ליגה, לפחות 3 מאותו מועדון, עד 4 מועדונים, לפחות 2 מדינות, כל הכרטיסים זהב, וכימיה 12.',
    endsAt: MADRID_DREAMS_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: {
      chemistry: 12,
      maxSameLeague: 4,
      minSameClub: 3,
      maxClubs: 4,
      minNations: 2,
      minQuality: 'gold',
    },
    reward: 'חבילת זהב ענקית',
    clubs: [C.real],
    previewFormation: '433',
    previewSquad: MADRID_DREAMS_SQUAD,
    createdAt: '2026-09-24T10:00:00.000Z',
  },
  {
    id: 'sbc-mm-celtic',
    title: 'מרקי מאצ׳אפס · סלטיק נגד ריינג׳רס',
    kind: 'classic',
    requirements:
      'אתגר מסורתי מהסבב של 17 בספטמבר 2026. לפחות שחקן אחד מסקוטלנד, לפחות שני מועדונים, לפחות כרטיס כסף אחד, וכימיה 14. הפרס שפורסם: חבילת זהב קטנה.',
    endsAt: MM_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: {
      chemistry: 14,
      nationAtLeast: [{ nation: N.scotland, count: 1 }],
      minClubs: 2,
      minSilver: 1,
    },
    reward: 'חבילת זהב קטנה',
    clubs: [C.celtic, C.rangers],
    previewFormation: '433',
    previewSquad: {
      gk: 'pandur',
      lb: 'tierney',
      lcb: 'carter',
      rcb: 'souttar',
      rb: 'tavernier',
      lcm: 'mcgregor',
      cm: 'hatate',
      rcm: 'raskin',
      lw: 'maeda',
      st: 'dessers',
      rw: 'cerny',
    },
    createdAt: '2026-09-17T18:00:00.000Z',
  },
  {
    id: 'sbc-mm-porto',
    title: 'מרקי מאצ׳אפס · פורטו נגד בנפיקה',
    kind: 'classic',
    requirements:
      'לפחות 2 מליגה פורטוגל, לפחות 2 מפורטוגל, עד 6 ליגות, לפחות זהב אחד, כל הכרטיסים מכסף ומעלה, וכימיה 18.',
    endsAt: MM_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: {
      chemistry: 18,
      leagueAtLeast: [{ league: L.ligaPt, count: 2 }],
      nationAtLeast: [{ nation: N.portugal, count: 2 }],
      maxLeagues: 6,
      minGold: 1,
      minQuality: 'silver',
    },
    reward: 'חבילת שחקני אלקטרום קטנה',
    clubs: [C.porto, C.benfica],
    previewFormation: '433',
    previewSquad: {
      gk: 'costa',
      lb: 'nuno',
      lcb: 'kiwior',
      rcb: 'silva',
      rb: 'bah',
      lcm: 'florentino',
      cm: 'kokcu',
      rcm: 'eustaquio',
      lw: 'galeno',
      st: 'gyokeres',
      rw: 'conceicao',
    },
    createdAt: '2026-09-17T18:00:00.000Z',
  },
  {
    id: 'sbc-mm-psg',
    title: 'מרקי מאצ׳אפס · פ.ס.ז׳ נגד מרסיי',
    kind: 'classic',
    requirements:
      'לפחות שחקן אחד מפריז סן ז׳רמן או אולימפיק מרסיי, לפחות 2 מצרפת, עד 5 מאותה ליגה, לפחות זהב אחד, כל הכרטיסים מכסף ומעלה, וכימיה 22.',
    endsAt: MM_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: {
      chemistry: 22,
      clubsAtLeast: { clubs: [C.psg, C.om], count: 1 },
      nationAtLeast: [{ nation: N.france, count: 2 }],
      maxSameLeague: 5,
      minGold: 1,
      minQuality: 'silver',
    },
    reward: 'חבילת זהב',
    clubs: [C.psg, C.om],
    previewFormation: '433',
    previewSquad: {
      gk: 'alisson',
      lb: 'robertson',
      lcb: 'vandijk',
      rcb: 'konate',
      rb: 'porro',
      lcm: 'vitinha',
      cm: 'bellingham',
      rcm: 'valverde',
      lw: 'vinicius',
      st: 'mbappe',
      rw: 'rodrygo',
    },
    createdAt: '2026-09-17T18:00:00.000Z',
  },
  {
    id: 'sbc-mm-madrid',
    title: 'מרקי מאצ׳אפס · ריאל מדריד נגד אתלטיקו',
    kind: 'classic',
    requirements:
      'לפחות 2 מריאל מדריד או אתלטיקו מדריד, לפחות 2 מלה ליגה, לפחות 4 מאותה מדינה, עד 3 מאותו מועדון, דירוג קבוצה 75, וכימיה 26.',
    endsAt: MM_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: {
      chemistry: 26,
      clubsAtLeast: { clubs: [C.real, C.atletico], count: 2 },
      leagueAtLeast: [{ league: L.laliga, count: 2 }],
      sameNationAtLeast: 4,
      maxSameClub: 3,
      minRating: 75,
    },
    reward: 'חבילת שחקני אלקטרום',
    clubs: [C.real, C.atletico],
    previewFormation: '433',
    previewSquad: {
      gk: 'courtois',
      lb: 'balde',
      lcb: 'cubarsi',
      rcb: 'militao',
      rb: 'trent',
      lcm: 'pedri',
      cm: 'koke',
      rcm: 'depaul',
      lw: 'williams',
      st: 'griezmann',
      rw: 'kubo',
    },
    createdAt: '2026-09-17T18:00:00.000Z',
  },
  {
    id: 'sbc-otw-duo-1',
    title: 'Ones to Watch Duo Pick · מורה / גונזאלבש',
    kind: 'streamlined',
    requirements:
      'בחירה בין רודריגו מורה לבין פדרו גונזאלבש (Pote). Streamlined ב־20,000 נקודות פריט — בלי כימיה ובלי עמדות. אפשר כפילויות ולהגיש חלק ולחזור.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: 20000,
    rules: null,
    reward: 'בחירת כרטיס 83+ OTW',
    clubs: [],
    createdAt: '2026-09-19T14:00:00.000Z',
  },
  {
    id: 'sbc-otw-bouaddi',
    title: 'Ones to Watch · איוב בואדי',
    kind: 'streamlined',
    requirements:
      'Streamlined: 20,000 נקודות עבור כרטיס 83 של איוב בואדי. בלי כימיה ובלי עמדות. אפשר כפילויות, ואפשר להגיש חלק ולחזור אחר כך.',
    endsAt: BOUADDI_ENDS,
    createdBy: 'admin',
    targetScore: 20000,
    rules: null,
    reward: 'כרטיס 83+ · קשר אחורי',
    clubs: [],
    createdAt: '2026-09-19T12:00:00.000Z',
  },
  {
    id: 'sbc-upgrade-83',
    title: 'שדרוג 83+',
    kind: 'streamlined',
    requirements:
      'Streamlined: מגישים פריטים עד שמגיעים לניקוד היעד ומקבלים חבילה עם שחקן זהב נדיר בדירוג 83 ומעלה.',
    endsAt: UPGRADE_83_ENDS,
    createdBy: 'admin',
    targetScore: 2500,
    rules: null,
    reward: 'שחקן זהב 83+',
    clubs: [],
    createdAt: '2026-09-24T08:00:00.000Z',
  },
  {
    id: 'sbc-upgrade-79x2',
    title: 'שדרוג 2×79+',
    kind: 'streamlined',
    requirements:
      'Streamlined: מגישים פריטים ומקבלים חבילה עם שני שחקני זהב בדירוג 79 ומעלה (Three of the Best Player Pick).',
    endsAt: UPGRADE_79_ENDS,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: 'בחירת 2× שחקני 79+',
    clubs: [],
    createdAt: '2026-09-24T08:00:00.000Z',
  },
  {
    id: 'sbc-getting-started',
    title: 'מתחילים',
    kind: 'streamlined',
    requirements: 'אתגרי פתיחה קבועים להיכרות עם מערכת ה-SBC והשדרוגים. בלי תאריך סיום.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: 1000,
    rules: null,
    reward: 'חבילות פתיחה',
    clubs: [],
    createdAt: '2026-09-18T10:00:00.000Z',
  },
  {
    id: 'sbc-gold-reroll',
    title: 'גולד רי־רול',
    kind: 'streamlined',
    requirements: 'מחליפים פריטי זהב בחבילת 2× שחקני זהב 78+. חוזר ללא הגבלה.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: 1250,
    rules: null,
    reward: '2× שחקני זהב 78+',
    clubs: [],
    createdAt: '2026-09-18T10:00:00.000Z',
  },
  {
    id: 'sbc-bronze-silver-reroll',
    title: 'ארד וכסף רי־רול',
    kind: 'streamlined',
    requirements: 'מחליפים פריטי ארד/כסף בחבילת שחקן זהב 75+. חוזר ללא הגבלה.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: 500,
    rules: null,
    reward: 'שחקן זהב 75+',
    clubs: [],
    createdAt: '2026-09-18T10:00:00.000Z',
  },
  {
    id: 'sbc-gold-upgrade',
    title: 'שדרוג זהב',
    kind: 'classic',
    requirements: 'כל הכרטיסים זהב. אין דרישת כימיה. הפרס: חבילת שחקני זהב קטנה.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: null,
    rules: {
      chemistry: 0,
      minQuality: 'gold',
    },
    reward: 'חבילת שחקני זהב קטנה',
    clubs: [],
    previewFormation: '433',
    previewSquad: GOLD_UPGRADE_SQUAD,
    createdAt: '2026-09-18T10:00:00.000Z',
  },
  {
    id: 'sbc-silver-upgrade',
    title: 'שדרוג כסף',
    kind: 'classic',
    requirements: 'כל הכרטיסים כסף, בלי זהב ובלי ארד. הפרס: שחקן נדיר 75+.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: null,
    rules: {
      chemistry: 0,
      exactQuality: 'silver',
    },
    reward: 'שחקן נדיר 75+',
    clubs: [],
    previewFormation: '433',
    previewSquad: SILVER_UPGRADE_SQUAD,
    createdAt: '2026-09-18T10:00:00.000Z',
  },
  {
    id: 'sbc-bronze-upgrade',
    title: 'שדרוג ארד',
    kind: 'classic',
    requirements: 'כל הכרטיסים ארד. הפרס: שתי חבילות שחקני כסף.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: null,
    rules: {
      chemistry: 0,
      exactQuality: 'bronze',
    },
    reward: '×2 חבילת שחקני כסף',
    clubs: [],
    previewFormation: null,
    previewSquad: null,
    createdAt: '2026-09-18T10:00:00.000Z',
  },
  {
    id: 'sbc-league-nation-advanced',
    title: 'ליגה ומדינה מתקדם',
    kind: 'classic',
    requirements: 'סדרת אתגרי פאזל קבועים של ליגה ומדינה. הפרס הסופי: חבילת זהב גדולה + מטבעות.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: null,
    rules: null,
    reward: 'חבילת זהב גדולה',
    clubs: [],
    createdAt: '2026-09-18T11:00:00.000Z',
  },
  {
    id: 'sbc-nations-10',
    title: 'תרגול כימיה · 10 מדינות',
    kind: 'classic',
    requirements:
      'זה לא אתגר רשמי של EA. כך עובדת דרישת מדינות ב-SBC מסורתי: 11 שחקנים, לפחות 10 לאומים שונים, וכימיה 18.',
    endsAt: null,
    createdBy: 'admin',
    targetScore: null,
    rules: {
      chemistry: 18,
      minNations: 10,
    },
    reward: 'תרגול',
    clubs: [],
    previewFormation: '433',
    previewSquad: NATION_DRILL_SQUAD,
    createdAt: '2026-09-23T12:00:00.000Z',
  },
];

const byId = new Map(officialChallenges.map((challenge) => [challenge.id, challenge]));

export function catalogChallenge(id: string): SbcChallenge | undefined {
  return byId.get(id);
}

/** Official + custom SBCs; timed challenges drop off automatically after endsAt. */
export function mergeOfficialSbcs(remote: SbcChallenge[], at = Date.now()): SbcChallenge[] {
  const officialIds = new Set(officialChallenges.map((challenge) => challenge.id));
  const custom = remote.filter((challenge) => !officialIds.has(challenge.id) && !RETIRED_SBC_IDS.has(challenge.id));
  return [...officialChallenges, ...custom].filter((challenge) => isOpen(challenge, at));
}

const playersById = new Map(PLAYERS.map((player) => [player.id, player]));

export function placedPreview(squad: Record<string, string> | null | undefined): Record<string, FcPlayer | null> {
  const placed: Record<string, FcPlayer | null> = {};
  for (const [slot, id] of Object.entries(squad ?? {})) placed[slot] = playersById.get(id) ?? null;
  return placed;
}
