import { officialChallenges } from '@/lib/sbcCatalog';
import type { CareerChallenge, Database } from '@/lib/types';

/** Approved career challenges. Merged onto the live list so they stay visible. */
export const featuredCareerChallenges: CareerChallenge[] = [
  {
    id: 'ch-leeds-title',
    title: 'אליפות עם לידס',
    mode: 'player',
    rules:
      'יוצרים שחקן ומתחילים בלידס יונייטד. בעונה הראשונה זוכים באליפות הליגה שבה הקבוצה מתחילה. אסור לעבור מועדון באמצע העונה. רמת קושי מינימלית: World Class.',
    proofRequirements:
      'צילום של טבלת הליגה עם לידס במקום הראשון, צילום של מסך השחקן עם הסמל של לידס, וצילום של מסך ההגדרות עם World Class ומעלה.',
    shareCode: null,
    endsAt: null,
    createdBy: 'admin',
    createdAt: '2026-09-29T15:40:00.000Z',
  },
  {
    id: 'ch-championship-promotion',
    title: 'עלייה בלי רכש מבוגר',
    mode: 'manager',
    rules:
      'מתחילים בקבוצה מהצ׳מפיונשיפ. עד סוף העונה עולים לפרמייר ליג. עד חלון ינואר אסור לקנות שחקן מעל גיל 23. השאלות מותרות. רמת קושי מינימלית: World Class.',
    proofRequirements:
      'צילום של טבלת סוף העונה עם קו העלייה, וצילום של הסגל שבו רואים את הגילאים.',
    shareCode: null,
    endsAt: null,
    createdBy: 'admin',
    createdAt: '2026-09-29T15:40:00.000Z',
  },
];

export function mergeFeaturedCareer(list: CareerChallenge[]): CareerChallenge[] {
  const titles = new Set(list.map((challenge) => challenge.title));
  const missing = featuredCareerChallenges.filter((challenge) => !titles.has(challenge.title));
  return [...missing, ...list];
}

export const STORAGE_KEY = 'fc27-community-db-v1';

export function seedDatabase(): Database {
  return {
    sessionUserId: null,
    profiles: [
      {
        id: 'admin',
        displayName: 'אביאל',
        isAdmin: true,
        approvedCount: 6,
        reputation: 48,
        createdAt: '2026-09-18T10:00:00.000Z',
      },
      {
        id: 'maya',
        displayName: 'מאיה',
        isAdmin: false,
        approvedCount: 5,
        reputation: 62,
        createdAt: '2026-09-18T12:00:00.000Z',
      },
      {
        id: 'noam',
        displayName: 'נועם',
        isAdmin: false,
        approvedCount: 1,
        reputation: 8,
        createdAt: '2026-09-19T12:00:00.000Z',
      },
    ],
    careerChallenges: [
      ...featuredCareerChallenges,
      {
        id: 'ch-academy',
        title: 'רק שחקני אקדמיה עד ינואר',
        mode: 'manager',
        rules: 'מתחילים בקבוצת ליגה שנייה. עד חלון ינואר אסור לקנות שחקן מעל גיל 21, וצריך להעפיל בפלייאוף או לסיים בחצי העליון.',
        proofRequirements: 'צילום של טבלת הליגה וצילום של סגל שבו רואים את הגילאים.',
        shareCode: 'ACADEMY27',
        endsAt: '2026-10-20T21:00:00.000Z',
        createdBy: 'admin',
        createdAt: '2026-09-19T08:00:00.000Z',
      },
      {
        id: 'ch-debut',
        title: 'שער בכורה בליגה',
        mode: 'player',
        rules: 'יוצרים שחקן צעיר וצריכים לכבוש את שער הליגה הראשון לפני סוף אוקטובר.',
        proofRequirements: 'צילום של השער או של סטטיסטיקת השחקן עם לפחות שער אחד.',
        shareCode: null,
        endsAt: '2026-10-05T21:00:00.000Z',
        createdBy: 'admin',
        createdAt: '2026-09-19T09:00:00.000Z',
      },
    ],
    careerSubmissions: [
      {
        id: 'sub-maya-debut',
        challengeId: 'ch-debut',
        userId: 'maya',
        playerOrClubName: 'נועה אביב',
        note: 'שער בכורה במחזור הרביעי, דקה 78, אחרי עלייה מהספסל.',
        imageUris: ['placeholder'],
        status: 'approved',
        createdAt: '2026-09-21T18:30:00.000Z',
      },
      {
        id: 'sub-noam-academy',
        challengeId: 'ch-academy',
        userId: 'noam',
        playerOrClubName: 'הפועל רמת גן',
        note: 'אחרי 12 מחזורים במקום 6, בלי אף שחקן מעל 21.',
        imageUris: ['placeholder'],
        status: 'pending',
        createdAt: '2026-09-22T20:10:00.000Z',
      },
    ],
    futPosts: [
      {
        id: 'fut-maya-squad',
        userId: 'maya',
        kind: 'squad',
        formation: '4-2-3-1',
        platform: 'pc',
        body: 'הקבוצה לפתיחת העונה. מחפשת דירוג כנה על הקישור במרכז.',
        playerName: null,
        packRarity: null,
        imageUris: ['placeholder'],
        status: 'approved',
        createdAt: '2026-09-22T16:00:00.000Z',
      },
      {
        id: 'fut-noam-squad',
        userId: 'noam',
        kind: 'squad',
        formation: '4-3-3',
        platform: 'ps5',
        body: 'בניתי סביב כנפיים מהירים. אשמח לדעת אם זה כיף או רק מהיר.',
        playerName: null,
        packRarity: null,
        imageUris: ['placeholder'],
        status: 'approved',
        createdAt: '2026-09-22T19:20:00.000Z',
      },
      {
        id: 'fut-noam-pack',
        userId: 'noam',
        kind: 'pack',
        formation: null,
        platform: 'ps5',
        body: 'לא ציפיתי לזה בחבילה הראשונה של השבוע.',
        playerName: 'שחקן הולוגרפי',
        packRarity: 'holographic',
        imageUris: ['placeholder'],
        status: 'approved',
        createdAt: '2026-09-23T07:40:00.000Z',
      },
    ],
    futRatings: [
      {
        id: 'rate-1',
        postId: 'fut-maya-squad',
        userId: 'noam',
        fit: 5,
        fun: 4,
        creativity: 5,
        createdAt: '2026-09-22T17:00:00.000Z',
      },
      {
        id: 'rate-2',
        postId: 'fut-noam-squad',
        userId: 'maya',
        fit: 4,
        fun: 5,
        creativity: 3,
        createdAt: '2026-09-22T21:00:00.000Z',
      },
    ],
    futLikes: [],
    comments: [
      {
        id: 'cmt-1',
        targetType: 'fut_post',
        targetId: 'fut-maya-squad',
        userId: 'noam',
        preset: 'respect',
        body: 'הרכב נקי והקישור במרכז יושב טוב.',
        status: 'visible',
        createdAt: '2026-09-22T17:05:00.000Z',
      },
    ],
    groundsPosts: [
      {
        id: 'lfg-maya-cb',
        userId: 'maya',
        intent: 'need_player',
        platform: 'pc',
        position: 'בלם',
        division: '4',
        playerLevel: 28,
        skillRating: 1450,
        archetype: 'Boss · כוח',
        region: 'מרכז',
        hours: '',
        contactType: 'discord',
        contactValue: '',
        eaId: 'MayaFC27',
        gamertag: 'maya_pc',
        avatarUri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg/200px-Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg',
        levelImageUri: 'placeholder',
        levelVerified: true,
        levelStatus: 'approved',
        createdAt: '2026-09-22T15:00:00.000Z',
      },
      {
        id: 'lfg-maya-wing',
        userId: 'maya',
        intent: 'need_player',
        platform: 'pc',
        position: 'כנף',
        division: '4',
        playerLevel: 22,
        skillRating: 1450,
        archetype: 'Spark · כנף',
        region: 'מרכז',
        hours: '',
        contactType: 'discord',
        contactValue: '',
        eaId: 'MayaFC27',
        gamertag: 'maya_pc',
        avatarUri: null,
        levelImageUri: null,
        levelVerified: false,
        levelStatus: 'rejected',
        createdAt: '2026-09-21T15:00:00.000Z',
      },
      {
        id: 'lfg-noam',
        userId: 'noam',
        intent: 'looking_for_club',
        platform: 'ps5',
        position: 'קשר התקפי',
        division: '7',
        playerLevel: 12,
        skillRating: 980,
        archetype: 'Creator · יצירה',
        region: 'שרון',
        hours: '',
        contactType: 'discord',
        contactValue: '',
        eaId: 'NoamCreator',
        gamertag: 'noam_ps5',
        avatarUri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Jude_Bellingham_England_v_Ghana_23_June_2026-061_%28cropped%29.jpg/200px-Jude_Bellingham_England_v_Ghana_23_June_2026-061_%28cropped%29.jpg',
        levelImageUri: 'placeholder',
        levelVerified: false,
        levelStatus: 'pending',
        createdAt: '2026-09-23T08:15:00.000Z',
      },
    ],
    sbcChallenges: officialChallenges,
    sbcSolutions: [],
    reports: [],
    follows: [],
    messages: [],
  };
}
