const titles = {
  fullkrug: 'Niclas Füllkrug',
  havertz: 'Kai Havertz',
  jesus: 'Gabriel Jesus',
  tomori: 'Fikayo Tomori',
  kulusevski: 'Dejan Kulusevski',
  udogie: 'Destiny Udogie',
  solanke: 'Dominic Solanke',
  neto: 'Pedro Neto',
  cucurella: 'Marc Cucurella',
  sanchez: 'Robert Sánchez',
  colwill: 'Levi Colwill',
  nkunku: 'Christopher Nkunku',
  hojlund: 'Rasmus Højlund',
  mount: 'Mason Mount',
  shaw: 'Luke Shaw',
  onzana: 'André Onana',
  rashford: 'Marcus Rashford',
  garnacho: 'Alejandro Garnacho',
  amrabat: 'Sofyan Amrabat',
  antony: 'Antony (footballer, born 2000)',
  casemiro: 'Casemiro',
  varane: 'Raphaël Varane',
  grealish: 'Jack Grealish',
  bernardo: 'Bernardo Silva',
  stones: 'John Stones',
  walker: 'Kyle Walker',
  doku: 'Jérémy Doku',
  savinho: 'Savinho',
  kovacic: 'Mateo Kovačić',
  cerny: 'Václav Černý (footballer)',
  diomande: 'Mohamed Diomande',
  nuno: 'Nuno Mendes (footballer, born 2002)',
  pepe: 'Pepe (footballer, born 1983)',
  eustaquio: 'Stephen Eustáquio',
  gyokeres: 'Viktor Gyökeres',
  conceicao: 'Francisco Conceição',
  vitinha: 'Vitinha (footballer, born 2000)',
  rodrygo: 'Rodrygo',
  militao: 'Éder Militão',
  pedri: 'Pedri',
  koke: 'Koke (footballer, born 1992)',
  depaul: 'Rodrigo De Paul',
  williams: 'Nico Williams',
  kubo: 'Takefusa Kubo',
  saliba: 'William Saliba',
  odegaard: 'Martin Ødegaard',
  macallister: 'Alexis Mac Allister',
  diaz: 'Luis Díaz (footballer, born 1997)',
  putellas: 'Alexia Putellas',
  dembele: 'Ousmane Dembélé',
  messi: 'Lionel Messi',
  kvara: 'Khvicha Kvaratskhelia',
  rudiger: 'Antonio Rüdiger',
  camavinga: 'Eduardo Camavinga',
  tchouameni: 'Aurélien Tchouaméni',
  arda: 'Arda Güler',
  alaba: 'David Alaba',
  oblak: 'Jan Oblak',
  alvarez: 'Julián Álvarez',
  sorloth: 'Alexander Sørloth',
  lenormand: 'Robin Le Normand',
  molina: 'Nahuel Molina',
  giuliano: 'Giuliano Simeone',
  llorente: 'Marcos Llorente',
  yamal: 'Lamine Yamal',
  lewandowski: 'Robert Lewandowski',
  kounde: 'Jules Koundé',
  araujo: 'Ronald Araújo',
  olmo: 'Dani Olmo',
  hakimi: 'Achraf Hakimi',
  marquinhos: 'Marquinhos',
  donnarumma: 'Gianluigi Donnarumma',
  barcola: 'Bradley Barcola',
  neves: 'João Neves',
  ruiz: 'Fabián Ruiz',
  zaire: 'Warren Zaïre-Emery',
  aubameyang: 'Pierre-Emerick Aubameyang',
  greenwood: 'Mason Greenwood',
  balerdi: 'Leonardo Balerdi',
  rongier: 'Valentin Rongier',
  luishenrique: 'Luis Henrique (footballer, born 2001)',
  meret: 'Alex Meret',
  condogno: 'Amine Harit',
  varela: 'Alan Varela',
  trubin: 'Anatoliy Trubin',
  akturkoglu: 'Kerem Aktürkoğlu',
  hjulmand: 'Morten Hjulmand',
  ralston: 'Anthony Ralston',
  montgomery: 'Adam Montgomery',
  trusty: 'Auston Trusty',
  king: 'Leon King (footballer)',
  salah: 'Mohamed Salah',
  gravenberch: 'Ryan Gravenberch',
  saka: 'Bukayo Saka',
  rice: 'Declan Rice',
  gabriel: 'Gabriel Magalhães',
  martinelli: 'Gabriel Martinelli',
  raya: 'David Raya',
  calafiori: 'Riccardo Calafiori',
  rodri: 'Rodri (footballer, born 1996)',
  debruyne: 'Kevin De Bruyne',
  dias: 'Rúben Dias',
  foden: 'Phil Foden',
  gvardiol: 'Joško Gvardiol',
  marmoush: 'Omar Marmoush',
  ederson: 'Ederson (footballer, born 1993)',
  palmer: 'Cole Palmer',
  jackson: 'Nicolas Jackson',
  enzo: 'Enzo Fernández',
  caicedo: 'Moisés Caicedo',
  james: 'Reece James (footballer, born 1999)',
  bruno: 'Bruno Fernandes',
  mainoo: 'Kobbie Mainoo',
  dalot: 'Diogo Dalot',
  vicario: 'Guglielmo Vicario',
  maddison: 'James Maddison',
  guimaraes: 'Bruno Guimarães',
  mitoma: 'Kaoru Mitoma',
  watkins: 'Ollie Watkins',
  bailey: 'Leon Bailey',
  kane: 'Harry Kane',
  musiala: 'Jamal Musiala',
  kimmich: 'Joshua Kimmich',
  davies: 'Alphonso Davies',
  neuer: 'Manuel Neuer',
  wirtz: 'Florian Wirtz',
  xhaka: 'Granit Xhaka',
  boniface: 'Victor Boniface',
  schick: 'Patrik Schick',
  adeyemi: 'Karim Adeyemi',
  kobel: 'Gregor Kobel',
  lautaro: 'Lautaro Martínez',
  barella: 'Nicolò Barella',
  thuram: 'Marcus Thuram',
  bastoni: 'Alessandro Bastoni',
  calhanoglu: 'Hakan Çalhanoğlu',
  dimarco: 'Federico Dimarco',
  leao: 'Rafael Leão',
  theo: 'Theo Hernández',
  maignan: 'Mike Maignan',
  pulisic: 'Christian Pulisic',
  reijnders: 'Tijjani Reijnders',
  vlahovic: 'Dušan Vlahović',
  mckennie: 'Weston McKennie',
  bremer: 'Gleison Bremer',
  mctominay: 'Scott McTominay',
  osimhen: 'Victor Osimhen',
  icardi: 'Mauro Icardi',
  dybala: 'Paulo Dybala',
  dovbyk: 'Artem Dovbyk',
  depay: 'Memphis Depay',
  bergwijn: 'Steven Bergwijn',
  lang: 'Noa Lang',
  deketelaere: 'Charles De Ketelaere',
  neymar: 'Neymar',
  mane: 'Sadio Mané',
  koulibaly: 'Kalidou Koulibaly',
  busquets: 'Sergio Busquets',
  suarez: 'Luis Suárez',
  alba: 'Jordi Alba',
  lookman: 'Ademola Lookman',
  mikautadze: 'Georges Mikautadze',
  oyarzabal: 'Mikel Oyarzabal',
  simon: 'Unai Simón',
  mahrez: 'Riyad Mahrez',
  kante: "N'Golo Kanté",
  onaia: 'Azzedine Ounahi',
  elanga: 'Anthony Elanga',
  gordon: 'Anthony Gordon (footballer, born 2001)',
  trippier: 'Kieran Trippier',
  pope: 'Nick Pope (footballer)',
  sarr: 'Ismaïla Sarr',
  eze: 'Eberechi Eze',
  mateta: 'Jean-Philippe Mateta',
  paqueta: 'Lucas Paquetá',
  kudus: 'Mohammed Kudus',
  bowen: 'Jarrod Bowen',
  tielemans: 'Youri Tielemans',
  martinez: 'Emiliano Martínez',
  cash: 'Matty Cash',
  digne: 'Lucas Digne',
  ramsey: 'Jacob Ramsey',
  keane: 'Michael Keane (footballer, born 1993)',
  pickford: 'Jordan Pickford',
  tarkowski: 'James Tarkowski',
  nmecha: 'Felix Nmecha',
  sabitzer: 'Marcel Sabitzer',
  guirassy: 'Serhou Guirassy',
};

const ids = Object.keys(titles);
const found = {};
const missed = [];

function resolve(start, redirects, normalized) {
  let current = start;
  for (let i = 0; i < 6; i += 1) {
    const next = normalized.get(current) || redirects.get(current);
    if (!next || next === current) break;
    current = next;
  }
  return current;
}

for (let i = 0; i < ids.length; i += 40) {
  const slice = ids.slice(i, i + 40);
  const params = new URLSearchParams({
    action: 'query',
    format: 'json',
    redirects: '1',
    prop: 'pageimages',
    piprop: 'thumbnail|original',
    pithumbsize: '400',
    titles: slice.map((id) => titles[id]).join('|'),
  });
  const response = await fetch(`https://en.wikipedia.org/w/api.php?${params}`, {
    headers: { 'User-Agent': 'fc27-israel-dev/1.0 (portrait lookup for a community app)' },
  });
  if (!response.ok) throw new Error(`wiki ${response.status}`);
  const data = await response.json();
  const redirects = new Map((data.query.redirects || []).map((row) => [row.from, row.to]));
  const normalized = new Map((data.query.normalized || []).map((row) => [row.from, row.to]));
  const pages = new Map(Object.values(data.query.pages || {}).map((page) => [page.title, page]));
  for (const id of slice) {
    const page = pages.get(resolve(titles[id], redirects, normalized));
    const source = page?.thumbnail?.source || '';
    if (source.includes('/wikipedia/commons/')) found[id] = { en: titles[id].replace(/ \(.*\)$/, ''), photo: source };
    else missed.push(`${id} ${page?.title || 'missing'} ${source || 'no-image'}`);
  }
}

import { writeFileSync } from 'node:fs';
writeFileSync('scripts/photos.json', JSON.stringify({ found, missed }, null, 2));
console.log('found', Object.keys(found).length);
console.log(missed.join('\n'));
